using Microsoft.AspNetCore.Localization;
using System.Globalization;


public static class LanguageHelper
{
    public static CultureInfo[] SupportedCultures = new[]
    {
        new CultureInfo("zh-Hans"), //This will be the default application culture
        new CultureInfo("en"),
        new CultureInfo("de"),
        new CultureInfo("zh-Hant"),
    };
    public static void SetDefaultCulture(this IServiceCollection services)
    {
        services.Configure<RequestLocalizationOptions>(options =>
        {
            options.DefaultRequestCulture = new RequestCulture(SupportedCultures.First());
            options.SupportedCultures = SupportedCultures;
            options.SupportedUICultures = SupportedCultures;
            options.RequestCultureProviders.Add(new CookieRequestCultureProvider());
        });
    }
    public static void SetRequestLocalization(this WebApplication app)
    {
        var _supportedCultures = SupportedCultures.Select(i=>i.IetfLanguageTag).ToArray();
        var localizationOptions = new RequestLocalizationOptions().SetDefaultCulture(_supportedCultures[0])
            .AddSupportedCultures(_supportedCultures)
            .AddSupportedUICultures(_supportedCultures);
        localizationOptions.RequestCultureProviders = new List<IRequestCultureProvider>
        {
            new CookieRequestCultureProvider()
        };
        app.UseRequestLocalization(localizationOptions);
    }
    public static void SetLanguage(string languagecode, string? redirectUri, HttpRequest request)
        {
            //string? languagecode = request.Query.FirstOrDefault(i => i.Key.Equals("langcode", StringComparison.OrdinalIgnoreCase)).Value;
            //string? redirectUri = request.Query.FirstOrDefault(i => i.Key.Equals("redirectUri", StringComparison.OrdinalIgnoreCase)).Value;
            if (redirectUri == null) redirectUri = "/";
            if (languagecode != null)
            {
                request.HttpContext.Response.Cookies.Append(
                Microsoft.AspNetCore.Localization.CookieRequestCultureProvider.DefaultCookieName,
                Microsoft.AspNetCore.Localization.CookieRequestCultureProvider.MakeCookieValue(new Microsoft.AspNetCore.Localization.RequestCulture(languagecode, languagecode)),
                    new CookieOptions
                    {
                        Expires = DateTimeOffset.UtcNow.AddYears(1),
                        IsEssential = true,
                        HttpOnly = false,
                        SameSite = SameSiteMode.None,
                        Secure = true
                    }
                );
            }

            request.HttpContext.Response.Redirect(redirectUri);
        }
    private static readonly Dictionary<string, string> LanguageNativeNames = new Dictionary<string, string>
    {
        {"aa", "Afar" },
        {"aa-DJ", "Afar (Djibouti)" },
        {"aa-ER", "Afar (Eritrea)" },
        {"aa-ET", "Afar (Ethiopia)" },
        {"af", "Afrikaans" },
        {"af-NA", "Afrikaans (Namibië)" },
        {"af-ZA", "Afrikaans (Suid-Afrika)" },
        {"agq", "Aghem" },
        {"agq-CM", "Aghem (Kàmàlûŋ)" },
        {"ak", "Akan" },
        {"ak-GH", "Akan (Gaana)" },
        {"am", "አማርኛ" },
        {"am-ET", "አማርኛ (ኢትዮጵያ)" },
        {"ar", "العربية" },
        {"ar-001", "العربية (العالم)" },
        {"ar-AE", "العربية (الإمارات العربية المتحدة)" },
        {"ar-BH", "العربية (البحرين)" },
        {"ar-DJ", "العربية (جيبوتي)" },
        {"ar-DZ", "العربية (الجزائر)" },
        {"ar-EG", "العربية (مصر)" },
        {"ar-ER", "العربية (إريتريا)" },
        {"ar-IL", "العربية (إسرائيل)" },
        {"ar-IQ", "العربية (العراق)" },
        {"ar-JO", "العربية (الأردن)" },
        {"ar-KM", "العربية (جزر القمر)" },
        {"ar-KW", "العربية (الكويت)" },
        {"ar-LB", "العربية (لبنان)" },
        {"ar-LY", "العربية (ليبيا)" },
        {"ar-MA", "العربية (المغرب)" },
        {"ar-MR", "العربية (موريتانيا)" },
        {"ar-OM", "العربية (عُمان)" },
        {"ar-PS", "العربية (السلطة الفلسطينية)" },
        {"ar-QA", "العربية (قطر)" },
        {"ar-SA", "العربية (المملكة العربية السعودية)" },
        {"ar-SD", "العربية (السودان)" },
        {"ar-SO", "العربية (الصومال)" },
        {"ar-SS", "العربية (جنوب السودان)" },
        {"ar-SY", "العربية (سوريا)" },
        {"ar-TD", "العربية (تشاد)" },
        {"ar-TN", "العربية (تونس)" },
        {"ar-YE", "العربية (اليمن)" },
        {"arn", "Mapudungun" },
        {"arn-CL", "Mapuche (Chile)" },
        {"as", "অসমীয়া" },
        {"as-IN", "অসমীয়া (ভাৰত)" },
        {"asa", "Kipare" },
        {"asa-TZ", "Kipare (Tadhania)" },
        {"ast", "asturianu" },
        {"ast-ES", "asturianu (España)" },
        {"az", "azərbaycan" },
        {"az-Cyrl", "азәрбајҹан (Кирил)" },
        {"az-Cyrl-AZ", "азәрбајҹан (Кирил, Азәрбајҹан)" },
        {"az-Latn", "azərbaycan (latın)" },
        {"az-Latn-AZ", "azərbaycan (latın, Azərbaycan)" },
        {"ba", "Bashkir" },
        {"ba-RU", "Bashkir (Russia)" },
        {"bas", "Ɓàsàa" },
        {"bas-CM", "Ɓàsàa (Kàmɛ̀rûn)" },
        {"be", "беларуская" },
        {"be-BY", "беларуская (Беларусь)" },
        {"bem", "Ichibemba" },
        {"bem-ZM", "Ichibemba (Zambia)" },
        {"bez", "Hibena" },
        {"bez-TZ", "Hibena (Hutanzania)" },
        {"bg", "български" },
        {"bg-BG", "български (България)" },
        {"bm", "bamanakan" },
        {"bm-ML", "bamanakan (Mali)" },
        {"bn", "বাংলা" },
        {"bn-BD", "বাংলা (বাংলাদেশ)" },
        {"bn-IN", "বাংলা (ভারত)" },
        {"bo", "བོད་སྐད་" },
        {"bo-CN", "བོད་སྐད་ (རྒྱ་ནག)" },
        {"bo-IN", "བོད་སྐད་ (རྒྱ་གར་)" },
        {"br", "brezhoneg" },
        {"br-FR", "brezhoneg (Frañs)" },
        {"brx", "बड़ो" },
        {"brx-IN", "बड़ो (भारत)" },
        {"bs", "bosanski" },
        {"bs-Cyrl", "босански (ћирилица)" },
        {"bs-Cyrl-BA", "босански (ћирилица, Босна и Херцеговина)" },
        {"bs-Latn", "bosanski (latinica)" },
        {"bs-Latn-BA", "bosanski (latinica, Bosna i Hercegovina)" },
        {"byn", "Blin" },
        {"byn-ER", "Blin (Eritrea)" },
        {"ca", "català" },
        {"ca-AD", "català (Andorra)" },
        {"ca-ES", "català (Espanya)" },
        {"ca-ES-VALENCIA", "valencià (Espanya, valencià)" },
        {"ca-FR", "català (França)" },
        {"ca-IT", "català (Itàlia)" },
        {"ccp", "𑄌𑄋𑄴𑄟𑄳𑄦" },
        {"ccp-BD", "𑄌𑄋𑄴𑄟𑄳𑄦 (𑄝𑄁𑄣𑄘𑄬𑄌𑄴)" },
        {"ccp-IN", "𑄌𑄋𑄴𑄟𑄳𑄦 (𑄞𑄢𑄧𑄖𑄴)" },
        {"ce", "нохчийн" },
        {"ce-RU", "нохчийн (Росси)" },
        {"ceb", "Cebuano" },
        {"ceb-PH", "Cebuano (Pilipinas)" },
        {"cgg", "Rukiga" },
        {"cgg-UG", "Rukiga (Uganda)" },
        {"chr", "ᏣᎳᎩ" },
        {"chr-US", "ᏣᎳᎩ (ᏌᏊ ᎢᏳᎾᎵᏍᏔᏅ ᏍᎦᏚᎩ)" },
        {"ckb", "کوردیی ناوەندی" },
        {"ckb-IQ", "کوردیی ناوەندی (عێراق)" },
        {"ckb-IR", "کوردیی ناوەندی (ئێران)" },
        {"co", "Corsican" },
        {"co-FR", "Corsican (France)" },
        {"cs", "čeština" },
        {"cs-CZ", "čeština (Česko)" },
        {"cu", "Church Slavic" },
        {"cu-RU", "Church Slavic (Russia)" },
        {"cy", "Cymraeg" },
        {"cy-GB", "Cymraeg (Y Deyrnas Unedig)" },
        {"da", "dansk" },
        {"da-DK", "dansk (Danmark)" },
        {"da-GL", "dansk (Grønland)" },
        {"dav", "Kitaita" },
        {"dav-KE", "Kitaita (Kenya)" },
        {"de", "Deutsch" },
        {"de-AT", "Deutsch (Österreich)" },
        {"de-BE", "Deutsch (Belgien)" },
        {"de-CH", "Deutsch (Schweiz)" },
        {"de-DE", "Deutsch (Deutschland)" },
        {"de-IT", "Deutsch (Italien)" },
        {"de-LI", "Deutsch (Liechtenstein)" },
        {"de-LU", "Deutsch (Luxemburg)" },
        {"dje", "Zarmaciine" },
        {"dje-NE", "Zarmaciine (Nižer)" },
        {"dsb", "dolnoserbšćina" },
        {"dsb-DE", "dolnoserbšćina (Nimska)" },
        {"dua", "duálá" },
        {"dua-CM", "duálá (Cameroun)" },
        {"dv", "Divehi" },
        {"dv-MV", "Divehi (Maldives)" },
        {"dyo", "joola" },
        {"dyo-SN", "joola (Senegal)" },
        {"dz", "རྫོང་ཁ" },
        {"dz-BT", "རྫོང་ཁ། (འབྲུག།)" },
        {"ebu", "Kĩembu" },
        {"ebu-KE", "Kĩembu (Kenya)" },
        {"ee", "Eʋegbe" },
        {"ee-GH", "Eʋegbe (Ghana nutome)" },
        {"ee-TG", "Eʋegbe (Togo nutome)" },
        {"el", "Ελληνικά" },
        {"el-CY", "Ελληνικά (Κύπρος)" },
        {"el-GR", "Ελληνικά (Ελλάδα)" },
        {"en", "English" },
        {"en-001", "English (World)" },
        {"en-150", "English (Europe)" },
        {"en-AE", "English (United Arab Emirates)" },
        {"en-AG", "English (Antigua & Barbuda)" },
        {"en-AI", "English (Anguilla)" },
        {"en-AS", "English (American Samoa)" },
        {"en-AT", "English (Austria)" },
        {"en-AU", "English (Australia)" },
        {"en-BB", "English (Barbados)" },
        {"en-BE", "English (Belgium)" },
        {"en-BI", "English (Burundi)" },
        {"en-BM", "English (Bermuda)" },
        {"en-BS", "English (Bahamas)" },
        {"en-BW", "English (Botswana)" },
        {"en-BZ", "English (Belize)" },
        {"en-CA", "English (Canada)" },
        {"en-CC", "English (Cocos [Keeling] Islands)" },
        {"en-CH", "English (Switzerland)" },
        {"en-CK", "English (Cook Islands)" },
        {"en-CM", "English (Cameroon)" },
        {"en-CX", "English (Christmas Island)" },
        {"en-CY", "English (Cyprus)" },
        {"en-DE", "English (Germany)" },
        {"en-DK", "English (Denmark)" },
        {"en-DM", "English (Dominica)" },
        {"en-ER", "English (Eritrea)" },
        {"en-FI", "English (Finland)" },
        {"en-FJ", "English (Fiji)" },
        {"en-FK", "English (Falkland Islands)" },
        {"en-FM", "English (Micronesia)" },
        {"en-GB", "English (United Kingdom)" },
        {"en-GD", "English (Grenada)" },
        {"en-GG", "English (Guernsey)" },
        {"en-GH", "English (Ghana)" },
        {"en-GI", "English (Gibraltar)" },
        {"en-GM", "English (Gambia)" },
        {"en-GU", "English (Guam)" },
        {"en-GY", "English (Guyana)" },
        {"en-HK", "English (Hong Kong SAR)" },
        {"en-IE", "English (Ireland)" },
        {"en-IL", "English (Israel)" },
        {"en-IM", "English (Isle of Man)" },
        {"en-IN", "English (India)" },
        {"en-IO", "English (British Indian Ocean Territory)" },
        {"en-JE", "English (Jersey)" },
        {"en-JM", "English (Jamaica)" },
        {"en-KE", "English (Kenya)" },
        {"en-KI", "English (Kiribati)" },
        {"en-KN", "English (St. Kitts & Nevis)" },
        {"en-KY", "English (Cayman Islands)" },
        {"en-LC", "English (St. Lucia)" },
        {"en-LR", "English (Liberia)" },
        {"en-LS", "English (Lesotho)" },
        {"en-MG", "English (Madagascar)" },
        {"en-MH", "English (Marshall Islands)" },
        {"en-MO", "English (Macao SAR)" },
        {"en-MP", "English (Northern Mariana Islands)" },
        {"en-MS", "English (Montserrat)" },
        {"en-MT", "English (Malta)" },
        {"en-MU", "English (Mauritius)" },
        {"en-MW", "English (Malawi)" },
        {"en-MY", "English (Malaysia)" },
        {"en-NA", "English (Namibia)" },
        {"en-NF", "English (Norfolk Island)" },
        {"en-NG", "English (Nigeria)" },
        {"en-NL", "English (Netherlands)" },
        {"en-NR", "English (Nauru)" },
        {"en-NU", "English (Niue)" },
        {"en-NZ", "English (New Zealand)" },
        {"en-PG", "English (Papua New Guinea)" },
        {"en-PH", "English (Philippines)" },
        {"en-PK", "English (Pakistan)" },
        {"en-PN", "English (Pitcairn Islands)" },
        {"en-PR", "English (Puerto Rico)" },
        {"en-PW", "English (Palau)" },
        {"en-RW", "English (Rwanda)" },
        {"en-SB", "English (Solomon Islands)" },
        {"en-SC", "English (Seychelles)" },
        {"en-SD", "English (Sudan)" },
        {"en-SE", "English (Sweden)" },
        {"en-SG", "English (Singapore)" },
        {"en-SH", "English (St Helena, Ascension, Tristan da Cunha)" },
        {"en-SI", "English (Slovenia)" },
        {"en-SL", "English (Sierra Leone)" },
        {"en-SS", "English (South Sudan)" },
        {"en-SX", "English (Sint Maarten)" },
        {"en-SZ", "English (Eswatini)" },
        {"en-TC", "English (Turks & Caicos Islands)" },
        {"en-TK", "English (Tokelau)" },
        {"en-TO", "English (Tonga)" },
        {"en-TT", "English (Trinidad & Tobago)" },
        {"en-TV", "English (Tuvalu)" },
        {"en-TZ", "English (Tanzania)" },
        {"en-UG", "English (Uganda)" },
        {"en-UM", "English (U.S. Outlying Islands)" },
        {"en-US", "English (United States)" },
        {"en-US-POSIX", "English (United States, Computer)" },
        {"en-VC", "English (St. Vincent & Grenadines)" },
        {"en-VG", "English (British Virgin Islands)" },
        {"en-VI", "English (U.S. Virgin Islands)" },
        {"en-VU", "English (Vanuatu)" },
        {"en-WS", "English (Samoa)" },
        {"en-ZA", "English (South Africa)" },
        {"en-ZM", "English (Zambia)" },
        {"en-ZW", "English (Zimbabwe)" },
        {"eo", "esperanto" },
        {"eo-001", "esperanto (Mondo)" },
        {"es", "español" },
        {"es-419", "español (Latinoamérica)" },
        {"es-AR", "español (Argentina)" },
        {"es-BO", "español (Bolivia)" },
        {"es-BR", "español (Brasil)" },
        {"es-BZ", "español (Belice)" },
        {"es-CL", "español (Chile)" },
        {"es-CO", "español (Colombia)" },
        {"es-CR", "español (Costa Rica)" },
        {"es-CU", "español (Cuba)" },
        {"es-DO", "español (República Dominicana)" },
        {"es-EC", "español (Ecuador)" },
        {"es-ES", "español (España)" },
        {"es-GQ", "español (Guinea Ecuatorial)" },
        {"es-GT", "español (Guatemala)" },
        {"es-HN", "español (Honduras)" },
        {"es-MX", "español (México)" },
        {"es-NI", "español (Nicaragua)" },
        {"es-PA", "español (Panamá)" },
        {"es-PE", "español (Perú)" },
        {"es-PH", "español (Filipinas)" },
        {"es-PR", "español (Puerto Rico)" },
        {"es-PY", "español (Paraguay)" },
        {"es-SV", "español (El Salvador)" },
        {"es-US", "español (Estados Unidos)" },
        {"es-UY", "español (Uruguay)" },
        {"es-VE", "español (Venezuela)" },
        {"et", "eesti" },
        {"et-EE", "eesti (Eesti)" },
        {"eu", "euskara" },
        {"eu-ES", "euskara (Espainia)" },
        {"ewo", "ewondo" },
        {"ewo-CM", "ewondo (Kamərún)" },
        {"fa", "فارسی" },
        {"fa-AF", "فارسی (افغانستان)" },
        {"fa-IR", "فارسی (ایران)" },
        {"ff", "Pulaar" },
        {"ff-Latn", "Fulah (Latin)" },
        {"ff-Latn-BF", "Fulah (Latin, Burkina Faso)" },
        {"ff-Latn-CM", "Fulah (Latin, Cameroon)" },
        {"ff-Latn-GH", "Fulah (Latin, Ghana)" },
        {"ff-Latn-GM", "Fulah (Latin, Gambia)" },
        {"ff-Latn-GN", "Fulah (Latin, Guinea)" },
        {"ff-Latn-GW", "Fulah (Latin, Guinea-Bissau)" },
        {"ff-Latn-LR", "Fulah (Latin, Liberia)" },
        {"ff-Latn-MR", "Fulah (Latin, Mauritania)" },
        {"ff-Latn-NE", "Fulah (Latin, Niger)" },
        {"ff-Latn-NG", "Fulah (Latin, Nigeria)" },
        {"ff-Latn-SL", "Fulah (Latin, Sierra Leone)" },
        {"ff-Latn-SN", "Fulah (Latin, Senegal)" },
        {"fi", "suomi" },
        {"fi-FI", "suomi (Suomi)" },
        {"fil", "Filipino" },
        {"fil-PH", "Filipino (Pilipinas)" },
        {"fo", "føroyskt" },
        {"fo-DK", "føroyskt (Danmark)" },
        {"fo-FO", "føroyskt (Føroyar)" },
        {"fr", "français" },
        {"fr-BE", "français (Belgique)" },
        {"fr-BF", "français (Burkina Faso)" },
        {"fr-BI", "français (Burundi)" },
        {"fr-BJ", "français (Bénin)" },
        {"fr-BL", "français (Saint-Barthélemy)" },
        {"fr-CA", "français (Canada)" },
        {"fr-CD", "français (Congo [République démocratique du])" },
        {"fr-CF", "français (République centrafricaine)" },
        {"fr-CG", "français (Congo)" },
        {"fr-CH", "français (Suisse)" },
        {"fr-CI", "français (Côte d’Ivoire)" },
        {"fr-CM", "français (Cameroun)" },
        {"fr-DJ", "français (Djibouti)" },
        {"fr-DZ", "français (Algérie)" },
        {"fr-FR", "français (France)" },
        {"fr-GA", "français (Gabon)" },
        {"fr-GF", "français (Guyane française)" },
        {"fr-GN", "français (Guinée)" },
        {"fr-GP", "français (Guadeloupe)" },
        {"fr-GQ", "français (Guinée équatoriale)" },
        {"fr-HT", "français (Haïti)" },
        {"fr-KM", "français (Comores)" },
        {"fr-LU", "français (Luxembourg)" },
        {"fr-MA", "français (Maroc)" },
        {"fr-MC", "français (Monaco)" },
        {"fr-MF", "français (Saint-Martin)" },
        {"fr-MG", "français (Madagascar)" },
        {"fr-ML", "français (Mali)" },
        {"fr-MQ", "français (Martinique)" },
        {"fr-MR", "français (Mauritanie)" },
        {"fr-MU", "français (Maurice)" },
        {"fr-NC", "français (Nouvelle-Calédonie)" },
        {"fr-NE", "français (Niger)" },
        {"fr-PF", "français (Polynésie française)" },
        {"fr-PM", "français (Saint-Pierre-et-Miquelon)" },
        {"fr-RE", "français (La Réunion)" },
        {"fr-RW", "français (Rwanda)" },
        {"fr-SC", "français (Seychelles)" },
        {"fr-SN", "français (Sénégal)" },
        {"fr-SY", "français (Syrie)" },
        {"fr-TD", "français (Tchad)" },
        {"fr-TG", "français (Togo)" },
        {"fr-TN", "français (Tunisie)" },
        {"fr-VU", "français (Vanuatu)" },
        {"fr-WF", "français (Wallis-et-Futuna)" },
        {"fr-YT", "français (Mayotte)" },
        {"fur", "furlan" },
        {"fur-IT", "furlan (Italie)" },
        {"fy", "Frysk" },
        {"fy-NL", "Frysk (Nederlân)" },
        {"ga", "Gaeilge" },
        {"ga-IE", "Gaeilge (Éire)" },
        {"gd", "Gàidhlig" },
        {"gd-GB", "Gàidhlig (An Rìoghachd Aonaichte)" },
        {"gl", "galego" },
        {"gl-ES", "galego (España)" },
        {"gn", "Guarani" },
        {"gn-PY", "Guarani (Paraguay)" },
        {"gsw", "Schwiizertüütsch" },
        {"gsw-CH", "Schwiizertüütsch (Schwiiz)" },
        {"gsw-FR", "Elsässisch (Frànkrisch)" },
        {"gsw-LI", "Schwiizertüütsch (Liächteschtäi)" },
        {"gu", "ગુજરાતી" },
        {"gu-IN", "ગુજરાતી (ભારત)" },
        {"guz", "Ekegusii" },
        {"guz-KE", "Ekegusii (Kenya)" },
        {"gv", "Gaelg" },
        {"gv-IM", "Gaelg (Ellan Vannin)" },
        {"ha", "Hausa" },
        {"ha-GH", "Hausa (Gana)" },
        {"ha-NE", "Hausa (Nijar)" },
        {"ha-NG", "Hausa (Najeriya)" },
        {"haw", "ʻŌlelo Hawaiʻi" },
        {"haw-US", "ʻŌlelo Hawaiʻi (ʻAmelika Hui Pū ʻIa)" },
        {"he", "עברית" },
        {"he-IL", "עברית (ישראל)" },
        {"hi", "हिन्दी" },
        {"hi-IN", "हिन्दी (भारत)" },
        {"hr", "hrvatski" },
        {"hr-BA", "hrvatski (Bosna i Hercegovina)" },
        {"hr-HR", "hrvatski (Hrvatska)" },
        {"hsb", "hornjoserbšćina" },
        {"hsb-DE", "hornjoserbšćina (Němska)" },
        {"hu", "magyar" },
        {"hu-HU", "magyar (Magyarország)" },
        {"hy", "հայերեն" },
        {"hy-AM", "հայերեն (Հայաստան)" },
        {"ia", "interlingua" },
        {"ia-001", "interlingua (Mundo)" },
        {"id", "Indonesia" },
        {"id-ID", "Indonesia (Indonesia)" },
        {"ig", "Asụsụ Igbo" },
        {"ig-NG", "Asụsụ Igbo (Naịjịrịa)" },
        {"ii", "ꆈꌠꉙ" },
        {"ii-CN", "ꆈꌠꉙ (ꍏꇩ)" },
        {"is", "íslenska" },
        {"is-IS", "íslenska (Ísland)" },
        {"it", "italiano" },
        {"it-CH", "italiano (Svizzera)" },
        {"it-IT", "italiano (Italia)" },
        {"it-SM", "italiano (San Marino)" },
        {"it-VA", "italiano (Città del Vaticano)" },
        {"iu", "Inuktitut" },
        {"iu-CA", "Inuktitut (Canada)" },
        {"iu-Latn", "Inuktitut (Latin)" },
        {"iu-Latn-CA", "Inuktitut (Latin, Canada)" },
        {"ja", "日本語" },
        {"ja-JP", "日本語 (日本)" },
        {"jgo", "Ndaꞌa" },
        {"jgo-CM", "Ndaꞌa (Kamɛlûn)" },
        {"jmc", "Kimachame" },
        {"jmc-TZ", "Kimachame (Tanzania)" },
        {"jv", "Jawa" },
        {"jv-ID", "Jawa (Indonésia)" },
        {"ka", "ქართული" },
        {"ka-GE", "ქართული (საქართველო)" },
        {"kab", "Taqbaylit" },
        {"kab-DZ", "Taqbaylit (Lezzayer)" },
        {"kam", "Kikamba" },
        {"kam-KE", "Kikamba (Kenya)" },
        {"kde", "Chimakonde" },
        {"kde-TZ", "Chimakonde (Tanzania)" },
        {"kea", "kabuverdianu" },
        {"kea-CV", "kabuverdianu (Kabu Verdi)" },
        {"khq", "Koyra ciini" },
        {"khq-ML", "Koyra ciini (Maali)" },
        {"ki", "Gikuyu" },
        {"ki-KE", "Gikuyu (Kenya)" },
        {"kk", "қазақ тілі" },
        {"kk-KZ", "қазақ тілі (Қазақстан)" },
        {"kkj", "kakɔ" },
        {"kkj-CM", "kakɔ (Kamɛrun)" },
        {"kl", "kalaallisut" },
        {"kl-GL", "kalaallisut (Kalaallit Nunaat)" },
        {"kln", "Kalenjin" },
        {"kln-KE", "Kalenjin (Emetab Kenya)" },
        {"km", "ខ្មែរ" },
        {"km-KH", "ខ្មែរ (កម្ពុជា)" },
        {"kn", "ಕನ್ನಡ" },
        {"kn-IN", "ಕನ್ನಡ (ಭಾರತ)" },
        {"ko", "한국어" },
        {"ko-KP", "한국어(조선민주주의인민공화국)" },
        {"ko-KR", "한국어(대한민국)" },
        {"kok", "कोंकणी" },
        {"kok-IN", "कोंकणी (भारत)" },
        {"ks", "کٲشُر" },
        {"ks-IN", "کٲشُر (ہِندوستان)" },
        {"ksb", "Kishambaa" },
        {"ksb-TZ", "Kishambaa (Tanzania)" },
        {"ksf", "rikpa" },
        {"ksf-CM", "rikpa (kamɛrún)" },
        {"ksh", "Kölsch" },
        {"ksh-DE", "Kölsch en Doütschland" },
        {"kw", "kernewek" },
        {"kw-GB", "kernewek (Rywvaneth Unys)" },
        {"ky", "кыргызча" },
        {"ky-KG", "кыргызча (Кыргызстан)" },
        {"lag", "Kɨlaangi" },
        {"lag-TZ", "Kɨlaangi (Taansanía)" },
        {"lb", "Lëtzebuergesch" },
        {"lb-LU", "Lëtzebuergesch (Lëtzebuerg)" },
        {"lg", "Luganda" },
        {"lg-UG", "Luganda (Yuganda)" },
        {"lkt", "Lakȟólʼiyapi" },
        {"lkt-US", "Lakȟólʼiyapi (Mílahaŋska Tȟamákȟočhe)" },
        {"ln", "lingála" },
        {"ln-AO", "lingála (Angóla)" },
        {"ln-CD", "lingála (Republíki ya Kongó Demokratíki)" },
        {"ln-CF", "lingála (Repibiki ya Afríka ya Káti)" },
        {"ln-CG", "lingála (Kongo)" },
        {"lo", "ລາວ" },
        {"lo-LA", "ລາວ (ລາວ)" },
        {"lrc", "لۊری شومالی" },
        {"lrc-IQ", "Northern Luri (Iraq)" },
        {"lrc-IR", "Northern Luri (Iran)" },
        {"lt", "lietuvių" },
        {"lt-LT", "lietuvių (Lietuva)" },
        {"lu", "Tshiluba" },
        {"lu-CD", "Tshiluba (Ditunga wa Kongu)" },
        {"luo", "Dholuo" },
        {"luo-KE", "Dholuo (Kenya)" },
        {"luy", "Luluhia" },
        {"luy-KE", "Luluhia (Kenya)" },
        {"lv", "latviešu" },
        {"lv-LV", "latviešu (Latvija)" },
        {"mas", "Maa" },
        {"mas-KE", "Maa (Kenya)" },
        {"mas-TZ", "Maa (Tansania)" },
        {"mer", "Kĩmĩrũ" },
        {"mer-KE", "Kĩmĩrũ (Kenya)" },
        {"mfe", "kreol morisien" },
        {"mfe-MU", "kreol morisien (Moris)" },
        {"mg", "Malagasy" },
        {"mg-MG", "Malagasy (Madagasikara)" },
        {"mgh", "Makua" },
        {"mgh-MZ", "Makua (Umozambiki)" },
        {"mgo", "metaʼ" },
        {"mgo-CM", "metaʼ (Kamalun)" },
        {"mi", "Māori" },
        {"mi-NZ", "Māori (Aotearoa)" },
        {"mk", "македонски" },
        {"mk-MK", "македонски (Северна Македонија)" },
        {"ml", "മലയാളം" },
        {"ml-IN", "മലയാളം (ഇന്ത്യ)" },
        {"mn", "монгол" },
        {"mn-MN", "монгол (Монгол)" },
        {"mn-Mong", "Mongolian (Mongolian)" },
        {"mn-Mong-CN", "Mongolian (Mongolian, China)" },
        {"mn-Mong-MN", "ᠮᠣᠩᠭᠣᠯ (ᠮᠣᠩᠭᠣᠯ ᠪᠢᠴᠢᠭ᠌, ᠮᠣᠩᠭᠣᠯ)" },
        {"moh", "Kanienʼkéha" },
        {"moh-CA", "Mohawk (Canada)" },
        {"mr", "मराठी" },
        {"mr-IN", "मराठी (भारत)" },
        {"ms", "Melayu" },
        {"ms-BN", "Melayu (Brunei)" },
        {"ms-MY", "Melayu (Malaysia)" },
        {"ms-SG", "Melayu (Singapura)" },
        {"mt", "Malti" },
        {"mt-MT", "Malti (Malta)" },
        {"mua", "MUNDAŊ" },
        {"mua-CM", "MUNDAŊ (kameruŋ)" },
        {"my", "မြန်မာ" },
        {"my-MM", "မြန်မာ (မြန်မာ)" },
        {"mzn", "مازرونی" },
        {"mzn-IR", "مازرونی (ایران)" },
        {"naq", "Khoekhoegowab" },
        {"naq-NA", "Khoekhoegowab (Namibiab)" },
        {"nb", "norsk bokmål" },
        {"nb-NO", "norsk bokmål (Norge)" },
        {"nb-SJ", "norsk bokmål (Svalbard og Jan Mayen)" },
        {"nd", "isiNdebele" },
        {"nd-ZW", "isiNdebele (Zimbabwe)" },
        {"nds", "Low German" },
        {"nds-DE", "Low German (Germany)" },
        {"nds-NL", "Low German (Netherlands)" },
        {"ne", "नेपाली" },
        {"ne-IN", "नेपाली (भारत)" },
        {"ne-NP", "नेपाली (नेपाल)" },
        {"nl", "Nederlands" },
        {"nl-AW", "Nederlands (Aruba)" },
        {"nl-BE", "Nederlands (België)" },
        {"nl-BQ", "Nederlands (Bonaire, Sint Eustatius en Saba)" },
        {"nl-CW", "Nederlands (Curaçao)" },
        {"nl-NL", "Nederlands (Nederland)" },
        {"nl-SR", "Nederlands (Suriname)" },
        {"nl-SX", "Nederlands (Sint-Maarten)" },
        {"nmg", "Kwasio" },
        {"nmg-CM", "Kwasio (Cameroon)" },
        {"nn", "nynorsk" },
        {"nn-NO", "nynorsk (Noreg)" },
        {"nnh", "Shwóŋò ngiembɔɔn" },
        {"nnh-CM", "Shwóŋò ngiembɔɔn (Kàmalûm)" },
        {"nqo", "N’Ko" },
        {"nqo-GN", "N’Ko (Guinea)" },
        {"nr", "South Ndebele" },
        {"nr-ZA", "South Ndebele (South Africa)" },
        {"nso", "Sesotho sa Leboa" },
        {"nso-ZA", "Sesotho sa Leboa (South Africa)" },
        {"nus", "Thok Nath" },
        {"nus-SS", "Nuer (South Sudan)" },
        {"nyn", "Runyankore" },
        {"nyn-UG", "Runyankore (Uganda)" },
        {"oc", "Occitan" },
        {"oc-FR", "Occitan (France)" },
        {"om", "Oromoo" },
        {"om-ET", "Oromoo (Itoophiyaa)" },
        {"om-KE", "Oromoo (Keeniyaa)" },
        {"or", "ଓଡ଼ିଆ" },
        {"or-IN", "ଓଡ଼ିଆ (ଭାରତ)" },
        {"os", "ирон" },
        {"os-GE", "ирон (Гуырдзыстон)" },
        {"os-RU", "ирон (Уӕрӕсе)" },
        {"pa", "ਪੰਜਾਬੀ" },
        {"pa-Arab", "پنجابی (عربی)" },
        {"pa-Arab-PK", "پنجابی (عربی, پاکستان)" },
        {"pa-Guru", "ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ)" },
        {"pa-Guru-IN", "ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ, ਭਾਰਤ)" },
        {"pl", "polski" },
        {"pl-PL", "polski (Polska)" },
        {"prg", "prūsiskan" },
        {"prg-001", "Prussian (World)" },
        {"ps", "پښتو" },
        {"ps-AF", "پښتو (افغانستان)" },
        {"ps-PK", "پښتو (پاکستان)" },
        {"pt", "português" },
        {"pt-AO", "português (Angola)" },
        {"pt-BR", "português (Brasil)" },
        {"pt-CH", "português (Suíça)" },
        {"pt-CV", "português (Cabo Verde)" },
        {"pt-GQ", "português (Guiné Equatorial)" },
        {"pt-GW", "português (Guiné-Bissau)" },
        {"pt-LU", "português (Luxemburgo)" },
        {"pt-MO", "português (RAE de Macau)" },
        {"pt-MZ", "português (Moçambique)" },
        {"pt-PT", "português (Portugal)" },
        {"pt-ST", "português (São Tomé e Príncipe)" },
        {"pt-TL", "português (Timor-Leste)" },
        {"qu", "Runasimi" },
        {"qu-BO", "Runasimi (Bolivia)" },
        {"qu-EC", "Runasimi (Ecuador)" },
        {"qu-PE", "Runasimi (Perú)" },
        {"quc", "Kʼicheʼ" },
        {"quc-GT", "Kʼicheʼ (Guatemala)" },
        {"rm", "rumantsch" },
        {"rm-CH", "rumantsch (Svizra)" },
        {"rn", "Ikirundi" },
        {"rn-BI", "Ikirundi (Uburundi)" },
        {"ro", "română" },
        {"ro-MD", "română (Republica Moldova)" },
        {"ro-RO", "română (România)" },
        {"rof", "Kihorombo" },
        {"rof-TZ", "Kihorombo (Tanzania)" },
        {"ru", "русский" },
        {"ru-BY", "русский (Беларусь)" },
        {"ru-KG", "русский (Киргизия)" },
        {"ru-KZ", "русский (Казахстан)" },
        {"ru-MD", "русский (Молдова)" },
        {"ru-RU", "русский (Россия)" },
        {"ru-UA", "русский (Украина)" },
        {"rw", "Kinyarwanda" },
        {"rw-RW", "Kinyarwanda (U Rwanda)" },
        {"rwk", "Kiruwa" },
        {"rwk-TZ", "Kiruwa (Tanzania)" },
        {"sa", "संस्कृत भाषा" },
        {"sa-IN", "Sanskrit (India)" },
        {"sah", "саха тыла" },
        {"sah-RU", "саха тыла (Арассыыйа)" },
        {"saq", "Kisampur" },
        {"saq-KE", "Kisampur (Kenya)" },
        {"sbp", "Ishisangu" },
        {"sbp-TZ", "Ishisangu (Tansaniya)" },
        {"sd", "سنڌي" },
        {"sd-PK", "سنڌي (پاڪستان)" },
        {"se", "davvisámegiella" },
        {"se-FI", "davvisámegiella (Suopma)" },
        {"se-NO", "davvisámegiella (Norga)" },
        {"se-SE", "davvisámegiella (Ruoŧŧa)" },
        {"seh", "sena" },
        {"seh-MZ", "sena (Moçambique)" },
        {"ses", "Koyraboro senni" },
        {"ses-ML", "Koyraboro senni (Maali)" },
        {"sg", "Sängö" },
        {"sg-CF", "Sängö (Ködörösêse tî Bêafrîka)" },
        {"shi", "ⵜⴰⵛⵍⵃⵉⵜ" },
        {"shi-Latn", "Tachelhit (Latin)" },
        {"shi-Latn-MA", "Tachelhit (Latin, Morocco)" },
        {"shi-Tfng", "Tachelhit (Tifinagh)" },
        {"shi-Tfng-MA", "Tachelhit (Tifinagh, Morocco)" },
        {"si", "සිංහල" },
        {"si-LK", "සිංහල (ශ්‍රී ලංකාව)" },
        {"sk", "slovenčina" },
        {"sk-SK", "slovenčina (Slovensko)" },
        {"sl", "slovenščina" },
        {"sl-SI", "slovenščina (Slovenija)" },
        {"sma", "Åarjelsaemien gïele" },
        {"sma-NO", "Southern Sami (Norway)" },
        {"sma-SE", "Southern Sami (Sweden)" },
        {"smj", "julevsámegiella" },
        {"smj-NO", "Lule Sami (Norway)" },
        {"smj-SE", "Lule Sami (Sweden)" },
        {"smn", "anarâškielâ" },
        {"smn-FI", "anarâškielâ (Suomâ)" },
        {"sms", "Skolt Sami" },
        {"sms-FI", "Skolt Sami (Finland)" },
        {"sn", "chiShona" },
        {"sn-ZW", "chiShona (Zimbabwe)" },
        {"so", "Soomaali" },
        {"so-DJ", "Soomaali (Jabuuti)" },
        {"so-ET", "Soomaali (Itoobiya)" },
        {"so-KE", "Soomaali (Kenya)" },
        {"so-SO", "Soomaali (Soomaaliya)" },
        {"sq", "shqip" },
        {"sq-AL", "shqip (Shqipëri)" },
        {"sq-MK", "shqip (Maqedonia e Veriut)" },
        {"sq-XK", "shqip (Kosovë)" },
        {"sr", "српски" },
        {"sr-Cyrl", "српски (ћирилица)" },
        {"sr-Cyrl-BA", "српски (ћирилица, Босна и Херцеговина)" },
        {"sr-Cyrl-ME", "српски (ћирилица, Црна Гора)" },
        {"sr-Cyrl-RS", "српски (ћирилица, Србија)" },
        {"sr-Cyrl-XK", "српски (ћирилица, Косово)" },
        {"sr-Latn", "srpski (latinica)" },
        {"sr-Latn-BA", "srpski (latinica, Bosna i Hercegovina)" },
        {"sr-Latn-ME", "srpski (latinica, Crna Gora)" },
        {"sr-Latn-RS", "srpski (latinica, Srbija)" },
        {"sr-Latn-XK", "srpski (latinica, Kosovo)" },
        {"ss", "siSwati" },
        {"ss-SZ", "siSwati (eSwatini)" },
        {"ss-ZA", "siSwati (South Africa)" },
        {"ssy", "Saho" },
        {"ssy-ER", "Saho (Eritrea)" },
        {"st", "Sesotho" },
        {"st-LS", "Sesotho (Lesotho)" },
        {"st-ZA", "Sesotho (South Africa)" },
        {"sv", "svenska" },
        {"sv-AX", "svenska (Åland)" },
        {"sv-FI", "svenska (Finland)" },
        {"sv-SE", "svenska (Sverige)" },
        {"sw", "Kiswahili" },
        {"sw-CD", "Kiswahili (Jamhuri ya Kidemokrasia ya Kongo)" },
        {"sw-KE", "Kiswahili (Kenya)" },
        {"sw-TZ", "Kiswahili (Tanzania)" },
        {"sw-UG", "Kiswahili (Uganda)" },
        {"syr", "Syriac" },
        {"syr-SY", "Syriac (Syria)" },
        {"ta", "தமிழ்" },
        {"ta-IN", "தமிழ் (இந்தியா)" },
        {"ta-LK", "தமிழ் (இலங்கை)" },
        {"ta-MY", "தமிழ் (மலேசியா)" },
        {"ta-SG", "தமிழ் (சிங்கப்பூர்)" },
        {"te", "తెలుగు" },
        {"te-IN", "తెలుగు (భారతదేశం)" },
        {"teo", "Kiteso" },
        {"teo-KE", "Kiteso (Kenia)" },
        {"teo-UG", "Kiteso (Uganda)" },
        {"tg", "тоҷикӣ" },
        {"tg-TJ", "тоҷикӣ (Тоҷикистон)" },
        {"th", "ไทย" },
        {"th-TH", "ไทย (ไทย)" },
        {"ti", "ትግርኛ" },
        {"ti-ER", "ትግርኛ (ኤርትራ)" },
        {"ti-ET", "ትግርኛ (ኢትዮጵያ)" },
        {"tig", "Tigre" },
        {"tig-ER", "Tigre (Eritrea)" },
        {"tk", "türkmen dili" },
        {"tk-TM", "türkmen dili (Türkmenistan)" },
        {"tn", "Setswana" },
        {"tn-BW", "Setswana (Botswana)" },
        {"tn-ZA", "Setswana (South Africa)" },
        {"to", "lea fakatonga" },
        {"to-TO", "lea fakatonga (Tonga)" },
        {"tr", "Türkçe" },
        {"tr-CY", "Türkçe (Kıbrıs)" },
        {"tr-TR", "Türkçe (Türkiye)" },
        {"ts", "Xitsonga" },
        {"ts-ZA", "Xitsonga (South Africa)" },
        {"tt", "татар" },
        {"tt-RU", "татар (Россия)" },
        {"twq", "Tasawaq senni" },
        {"twq-NE", "Tasawaq senni (Nižer)" },
        {"tzm", "Tamaziɣt n laṭlaṣ" },
        {"tzm-MA", "Tamaziɣt n laṭlaṣ (Meṛṛuk)" },
        {"ug", "ئۇيغۇرچە" },
        {"ug-CN", "ئۇيغۇرچە (جۇڭگو)" },
        {"uk", "українська" },
        {"uk-UA", "українська (Україна)" },
        {"ur", "اردو" },
        {"ur-IN", "اردو (بھارت)" },
        {"ur-PK", "اردو (پاکستان)" },
        {"uz", "o‘zbek" },
        {"uz-Arab", "اوزبیک (عربی)" },
        {"uz-Arab-AF", "اوزبیک (عربی, افغانستان)" },
        {"uz-Cyrl", "ўзбекча (Кирил)" },
        {"uz-Cyrl-UZ", "ўзбекча (Кирил, Ўзбекистон)" },
        {"uz-Latn", "o‘zbek (lotin)" },
        {"uz-Latn-UZ", "o‘zbek (lotin, Oʻzbekiston)" },
        {"vai", "ꕙꔤ" },
        {"vai-Latn", "Vai (Latin)" },
        {"vai-Latn-LR", "Vai (Latin, Liberia)" },
        {"vai-Vaii", "Vai (Vai)" },
        {"vai-Vaii-LR", "Vai (Vai, Liberia)" },
        {"ve", "Venda" },
        {"ve-ZA", "Venda (South Africa)" },
        {"vi", "Tiếng Việt" },
        {"vi-VN", "Tiếng Việt (Việt Nam)" },
        {"vo", "Volapük" },
        {"vo-001", "Volapük (World)" },
        {"vun", "Kyivunjo" },
        {"vun-TZ", "Kyivunjo (Tanzania)" },
        {"wae", "Walser" },
        {"wae-CH", "Walser (Schwiz)" },
        {"wal", "Wolaytta" },
        {"wal-ET", "Wolaytta (Ethiopia)" },
        {"wo", "Wolof" },
        {"wo-SN", "Wolof (Senegaal)" },
        {"xh", "isiXhosa" },
        {"xh-ZA", "isiXhosa (eMzantsi Afrika)" },
        {"xog", "Olusoga" },
        {"xog-UG", "Olusoga (Yuganda)" },
        {"yav", "nuasue" },
        {"yav-CM", "nuasue (Kemelún)" },
        {"yi", "ייִדיש" },
        {"yi-001", "ייִדיש (וועלט)" },
        {"yo", "Èdè Yorùbá" },
        {"yo-BJ", "Èdè Yorùbá (Orílɛ́ède Bɛ̀nɛ̀)" },
        {"yo-NG", "Èdè Yorùbá (Orilẹ̀-èdè Nàìjíríà)" },
        {"zgh", "ⵜⴰⵎⴰⵣⵉⵖⵜ" },
        {"zgh-MA", "ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵍⵎⵖⵔⵉⴱ)" },
        {"zh", "中文" },
        {"zh-Hans", "中文（简体）" },
        {"zh-Hans-CN", "中文（简体，中国）" },
        {"zh-Hans-HK", "中文（简体，香港特别行政区）" },
        {"zh-Hans-MO", "中文（简体，澳门特别行政区）" },
        {"zh-Hans-SG", "中文（简体，新加坡）" },
        {"zh-Hant", "中文（繁體）" },
        {"zh-Hant-HK", "中文（繁體字，香港特別行政區）" },
        {"zh-Hant-MO", "中文（繁體字，澳門特別行政區）" },
        {"zh-Hant-TW", "中文（繁體，台灣）" },
        {"zu", "isiZulu" },
        {"zu-ZA", "isiZulu (iNingizimu Afrika)" }
    };
    /// <summary>
    /// A workaround to get language native name.
    /// https://github.com/dotnet/runtime/issues/44739
    /// </summary>
    /// <param name="LanguageTag">
    /// RFC 4646 languagecode2 + country/regioncode(optional), for example: en-US, zh-CN, or simply en, zh
    /// </param>
    /// <returns>The display name of specified language code in native characters.</returns>
    public static string GetNativeName(string LanguageTag)
    {
        if (string.IsNullOrWhiteSpace(LanguageTag)) return "Unknown Language";
        if (!LanguageNativeNames.TryGetValue(LanguageTag, out var nativeName)) return "Unknown Language";
        return nativeName;
    }
}